############################################################
## INTEGRATION LOO × WGCNA — v5
## Figure A | Figure B | Export Cytoscape
##
## NOUVEAUTÉ : sélection manuelle des modules
##   → MODULES_MANUAL  : liste vos choix (prioritaire)
##   → MODULES_AUTO_N  : fallback automatique si vide
##   → Un résumé de TOUS les modules est imprimé au lancement
##     pour vous aider à choisir
############################################################

##############################
## PARTIE 1 — PARAMÈTRES
##############################
SEED <- 123
set.seed(SEED)
options(stringsAsFactors = FALSE)

## ── Chemins ────────────────────────────────────────────────────────────────
## USER CONFIGURATION
## Directory containing outputs from 03_edgeR_DEG_LOO_topGO.R
loo_dir   <- "/path/to/results/edgeR_LOO_topGO/02_DEG"

## Timestamped WGCNA output directory generated by 04_WGCNA.R
wgcna_dir <- "/path/to/results/WGCNA/WGCNA_Protection_ALL_YYYYMMDD_HHMMSS"

out_dir   <- file.path(wgcna_dir, "15_LOO_WGCNA_integration")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
dir_plots  <- file.path(out_dir, "01_plots");     dir.create(dir_plots,  recursive = TRUE, showWarnings = FALSE)
dir_tables <- file.path(out_dir, "02_tables");    dir.create(dir_tables, recursive = TRUE, showWarnings = FALSE)
dir_cyto   <- file.path(out_dir, "03_cytoscape"); dir.create(dir_cyto,   recursive = TRUE, showWarnings = FALSE)

## ══════════════════════════════════════════════════════════════════════════
## ██  SÉLECTION DES MODULES — MODIFIER ICI  ██
## ══════════════════════════════════════════════════════════════════════════
##
## Option A — MANUEL (recommandé) :
##   Listez les modules de votre choix ci-dessous.
##   Vous pouvez choisir autant de modules que vous voulez.
##   Le tableau récapitulatif sera imprimé au lancement du script
##   pour vous aider à décider.
##
##   Exemple :
##   MODULES_MANUAL <- c("greenyellow", "brown", "green", "turquoise", "red")
##
## Option B — AUTOMATIQUE :
##   Laissez MODULES_MANUAL <- c()  (vide)
##   Le script sélectionne automatiquement les MODULES_AUTO_N
##   premiers modules triés par FDR lmerTest.
##
## ══════════════════════════════════════════════════════════════════════════


MODULES_MANUAL <- c( "greenyellow", "brown","green","purple")

## Fallback automatique si MODULES_MANUAL est vide
## Combien de modules sélectionner automatiquement ?
MODULES_AUTO_N <- 5

## ── Cytoscape — contrôles réseau ───────────────────────────────────────────
CYTO_KME_MIN      <- 0.50   # kME minimum pour inclure un nœud
# → augmenter (ex: 0.60) si trop de nœuds
CYTO_MAX_NODES    <- 75     # max nœuds par module
CYTO_MAX_EDGES    <- 300    # max arêtes par module (évite le fully-connected)
CYTO_TOM_QUANTILE <- 0.85   # top X% arêtes TOM conservées (si fichiers TOM dispo)
CYTO_COR_THRESHOLD <- 0.70  # seuil corrélation si pas de TOM
CYTO_EDGE_METHOD  <- "auto" # "tom" | "cor" | "kme_product" | "auto"

##############################
## PARTIE 2 — Packages
##############################
load_pkgs <- function(pkgs) {
  for (p in pkgs) {
    if (!requireNamespace(p, quietly = TRUE)) install.packages(p, dependencies = TRUE)
    suppressPackageStartupMessages(library(p, character.only = TRUE))
  }
}
load_pkgs(c("dplyr","readr","tibble","tidyr","ggplot2","pheatmap",
            "ggrepel","svglite","scales","grid"))

##############################
## PARTIE 3 — Thème + helpers
##############################
theme_pub <- function(base_size = 11) {
  ggplot2::theme_classic(base_size = base_size) +
    ggplot2::theme(
      panel.border      = ggplot2::element_rect(colour = "black", fill = NA, linewidth = 0.8),
      panel.grid        = ggplot2::element_blank(),
      panel.background  = ggplot2::element_rect(fill = "white"),
      axis.line         = ggplot2::element_blank(),
      axis.ticks        = ggplot2::element_line(colour = "black", linewidth = 0.5),
      axis.ticks.length = ggplot2::unit(3, "mm"),
      axis.text         = ggplot2::element_text(colour = "black", size = base_size + 1),
      axis.title        = ggplot2::element_text(colour = "black", size = base_size + 2, face = "bold"),
      plot.title        = ggplot2::element_text(size = base_size + 4, face = "bold", hjust = 0),
      plot.subtitle     = ggplot2::element_text(size = base_size + 1, colour = "grey30"),
      legend.title      = ggplot2::element_text(size = base_size + 1, face = "bold"),
      legend.text       = ggplot2::element_text(size = base_size),
      legend.key.size   = ggplot2::unit(5, "mm")
    )
}

save_gg <- function(p, base_path, width = 8, height = 6, dpi = 600) {
  ggplot2::ggsave(paste0(base_path, ".pdf"), p, width = width, height = height, bg = "white")
  ggplot2::ggsave(paste0(base_path, ".png"), p, width = width, height = height,
                  dpi = dpi, bg = "white")
  svglite::svglite(paste0(base_path, ".svg"), width = width, height = height)
  print(p); grDevices::dev.off()
  message("   Saved: ", basename(base_path))
}

TIER_COLORS <- c(
  "Tier1_both"   = "#1A237E",
  "Tier1_P_only" = "#E53935",
  "Tier1_N_only" = "#00897B",
  "Tier2"        = "#F57F17",
  "Tier3"        = "#78909C",
  "NS"           = "#D5D8DC"
)
TIER_HEX <- c(
  "Tier1_both"   = "#1A237E",
  "Tier1_P_only" = "#E53935",
  "Tier1_N_only" = "#00897B",
  "Tier2"        = "#F57F17",
  "Tier3"        = "#78909C",
  "NS"           = "#BDBDBD"
)

##############################
## PARTIE 4 — Import
##############################
cat("════════════════════════════════════════\n")
cat("PARTIE 4 — Import\n")
cat("════════════════════════════════════════\n\n")

deg_file  <- file.path(loo_dir,   "DEG_Protection_mean.csv")
tier_file <- file.path(loo_dir,   "DEG_Tiers_Comparative.csv")
hub_file  <- file.path(wgcna_dir, "05_hub_genes", "All_genes_kME_GS_Protection.csv")
me_file   <- file.path(wgcna_dir, "04_module_trait", "tables",
                       "ME_Protection_mixedModel_PRIMARY.csv")

for (f in c(deg_file, tier_file, hub_file, me_file)) {
  stopifnot(file.exists(f))
  cat(" ✓", basename(f), "\n")
}

deg_df  <- readr::read_csv(deg_file,  show_col_types = FALSE)
tier_df <- readr::read_csv(tier_file, show_col_types = FALSE)
hub_df  <- readr::read_csv(hub_file,  show_col_types = FALSE)
me_df   <- readr::read_csv(me_file,   show_col_types = FALSE)

expr_rds <- file.path(wgcna_dir, "01_normalization",
                      "expr_mat_vst_BATCHCORRECTED_genes_x_samples.rds")
expr_mat <- if (file.exists(expr_rds)) { cat(" ✓ expr_mat\n"); readRDS(expr_rds) } else NULL

tom_dir  <- file.path(wgcna_dir, "08_Cytoscape")
has_tom  <- dir.exists(tom_dir) &&
  length(list.files(tom_dir, pattern = "edges_TOM\\.csv$")) > 0
cat(if (has_tom) " ✓ Fichiers TOM\n" else " ⚠  Pas de TOM\n")
cat("\n")

##############################
## PARTIE 5 — Jointure
##############################
integr_df <- hub_df |>
  dplyr::select(Gene, ModuleColor, ModuleLabel, kME_own, GS_Protection) |>
  dplyr::left_join(
    deg_df |> dplyr::select(Gene, log2FoldChange, padj, Status, aveLogCPM),
    by = "Gene") |>
  dplyr::left_join(
    tier_df |> dplyr::select(Gene, Tier_P, Tier_N, Tier_Global,
                             LOO_Score_P, LOO_Score_N),
    by = "Gene") |>
  dplyr::left_join(
    me_df |>
      dplyr::select(ME, ModuleColor, FDR, betaProtection) |>
      dplyr::rename(Module_ME = ME, Module_FDR = FDR, Module_beta = betaProtection),
    by = "ModuleColor") |>
  dplyr::mutate(
    Tier_Global = dplyr::coalesce(Tier_Global, "NS"),
    Tier_Global = factor(Tier_Global,
                         levels = c("Tier1_both","Tier1_P_only","Tier1_N_only",
                                    "Tier2","Tier3","NS")),
    Status = dplyr::coalesce(Status, "NS")
  )

readr::write_csv(integr_df, file.path(dir_tables, "T00_Integrated_full.csv"))

## ══════════════════════════════════════════════════════════════════════════
## TABLEAU RÉCAPITULATIF DE TOUS LES MODULES
## → Lisez ce tableau pour choisir vos modules (MODULES_MANUAL)
## ══════════════════════════════════════════════════════════════════════════
tier_counts <- integr_df |>
  dplyr::filter(!is.na(ModuleColor), ModuleColor != "grey") |>
  dplyr::group_by(ModuleColor) |>
  dplyr::summarise(
    N_genes      = dplyr::n(),
    N_Tier1_both = sum(Tier_Global == "Tier1_both",   na.rm = TRUE),
    N_Tier1_P    = sum(Tier_Global == "Tier1_P_only", na.rm = TRUE),
    N_Tier1_N    = sum(Tier_Global == "Tier1_N_only", na.rm = TRUE),
    N_Tier2      = sum(Tier_Global == "Tier2",        na.rm = TRUE),
    Pct_T1both   = round(100 * N_Tier1_both / dplyr::n(), 1),
    .groups = "drop"
  )

module_summary <- me_df |>
  dplyr::filter(!is.na(FDR), ModuleColor != "grey") |>
  dplyr::select(ME, ModuleColor, FDR, betaProtection) |>
  dplyr::left_join(tier_counts, by = "ModuleColor") |>
  dplyr::mutate(
    FDR_sig   = dplyr::case_when(
      FDR < 0.001 ~ "***",
      FDR < 0.01  ~ "**",
      FDR < 0.05  ~ "*",
      FDR < 0.10  ~ ".",
      TRUE        ~ "ns"
    ),
    Direction = dplyr::case_when(
      betaProtection > 0 ~ "↑ Protected",
      betaProtection < 0 ~ "↓ Protected",
      TRUE               ~ "—"
    )
  ) |>
  dplyr::arrange(FDR)

readr::write_csv(module_summary,
                 file.path(dir_tables, "T01_ALL_modules_summary.csv"))

cat("══════════════════════════════════════════════════════════════════════\n")
cat("TABLEAU DE TOUS LES MODULES — pour choisir MODULES_MANUAL\n")
cat("══════════════════════════════════════════════════════════════════════\n")
cat(sprintf("%-15s %-6s %-5s %-12s %-6s %8s %6s %6s %6s\n",
            "Module", "FDR", "Sig", "Direction",
            "Beta", "N_genes", "T1both", "Pct%", "T1P"))
cat(strrep("─", 72), "\n")
for (i in seq_len(nrow(module_summary))) {
  r <- module_summary[i,]
  cat(sprintf("%-15s %-6s %-5s %-12s %+6.3f %8d %6d %5.1f%% %6d\n",
              r$ModuleColor,
              formatC(r$FDR, format="e", digits=1),
              r$FDR_sig,
              r$Direction,
              dplyr::coalesce(r$betaProtection, 0),
              dplyr::coalesce(r$N_genes, 0L),
              dplyr::coalesce(r$N_Tier1_both, 0L),
              dplyr::coalesce(r$Pct_T1both, 0),
              dplyr::coalesce(r$N_Tier1_P, 0L)))
}
cat(strrep("─", 72), "\n")
cat("Sig : *** p<0.001 | ** p<0.01 | * p<0.05 | . p<0.10 | ns non-sig\n")
cat("T1both = Tier1_both | T1P = Tier1_P_only | Pct% = % du module\n")
cat("══════════════════════════════════════════════════════════════════════\n\n")

## ── Résolution MODULES_MANUAL vs auto ──────────────────────────────────────
if (length(MODULES_MANUAL) > 0) {
  
  ## Vérifier que les modules existent
  all_mods <- unique(integr_df$ModuleColor[!is.na(integr_df$ModuleColor) &
                                             integr_df$ModuleColor != "grey"])
  invalid  <- setdiff(MODULES_MANUAL, all_mods)
  if (length(invalid) > 0) {
    cat("⚠️  Modules non trouvés (vérifiez l'orthographe) :\n")
    cat("  ", paste(invalid, collapse=", "), "\n\n")
  }
  selected_modules <- intersect(MODULES_MANUAL, all_mods)
  cat("▶  Mode MANUEL —", length(selected_modules),
      "module(s) sélectionné(s) :\n")
  cat("  ", paste(selected_modules, collapse=", "), "\n\n")
  
} else {
  
  ## Fallback automatique — top N par FDR
  selected_modules <- module_summary |>
    dplyr::slice_head(n = MODULES_AUTO_N) |>
    dplyr::pull(ModuleColor)
  cat("▶  Mode AUTO (top", MODULES_AUTO_N, "par FDR) :\n")
  cat("  ", paste(selected_modules, collapse=", "), "\n\n")
}

##############################
## PARTIE 6 — FIGURE A
## Heatmap module × tier — TOUS les modules (pas seulement les sélectionnés)
## Les modules sélectionnés sont surlignés avec une annotation
##############################
cat("════════════════════════════════════════\n")
cat("PARTIE 6 — Figure A : module × tier\n")
cat("════════════════════════════════════════\n")

tier_col_order <- c("Tier1_both","Tier1_P_only","Tier1_N_only","Tier2","Tier3")

heat_df <- integr_df |>
  dplyr::filter(!is.na(ModuleColor), ModuleColor != "grey",
                Tier_Global %in% tier_col_order) |>
  dplyr::count(ModuleColor, Tier_Global, name = "N_genes") |>
  dplyr::group_by(ModuleColor) |>
  dplyr::mutate(Module_total = sum(N_genes),
                Percent = 100 * N_genes / Module_total) |>
  dplyr::ungroup()

heat_mat <- heat_df |>
  dplyr::select(ModuleColor, Tier_Global, Percent) |>
  tidyr::pivot_wider(names_from = Tier_Global, values_from = Percent,
                     values_fill = 0) |>
  as.data.frame()

tier_col_present <- tier_col_order[tier_col_order %in% colnames(heat_mat)]
rownames(heat_mat) <- heat_mat$ModuleColor
heat_mat$ModuleColor <- NULL
heat_mat <- as.matrix(heat_mat[, tier_col_present, drop = FALSE])
if ("Tier1_both" %in% colnames(heat_mat))
  heat_mat <- heat_mat[order(heat_mat[,"Tier1_both"], decreasing = TRUE), , drop = FALSE]

## Annotation : couleur du module + statut sélectionné
row_ann <- data.frame(
  Module    = rownames(heat_mat),
  Selected  = ifelse(rownames(heat_mat) %in% selected_modules,
                     "Sélectionné", "Autre"),
  FDR_sig   = dplyr::coalesce(
    module_summary$FDR_sig[match(rownames(heat_mat), module_summary$ModuleColor)],
    "ns"
  ),
  row.names = rownames(heat_mat)
)

mod_fill_colors <- setNames(
  ifelse(rownames(heat_mat) %in% grDevices::colors(),
         rownames(heat_mat), "#888888"),
  rownames(heat_mat)
)

ann_colors_A <- list(
  Module   = mod_fill_colors,
  Selected = c("Sélectionné" = "#FFD600", "Autre" = "#F5F5F5"),
  FDR_sig  = c("***" = "#7B1FA2", "**" = "#C2185B", "*" = "#E53935",
               "."  = "#F57F17", "ns" = "#BDBDBD")
)

for (ext in c("pdf","png")) {
  pheatmap::pheatmap(
    heat_mat,
    annotation_row    = row_ann,
    annotation_colors = ann_colors_A,
    color             = grDevices::colorRampPalette(
      c("white","#A8C7FA","#1A237E"))(100),
    cluster_rows      = FALSE,
    cluster_cols      = FALSE,
    border_color      = "grey85",
    fontsize          = 10,
    angle_col         = 45,
    display_numbers   = TRUE,
    number_format     = "%.1f",
    number_color      = "grey25",
    main              = "Module × LOO tier composition (%) — tous modules",
    filename          = file.path(dir_plots,
                                  paste0("FigA_Module_Tier_all.", ext)),
    width  = max(7, ncol(heat_mat) * 1.4 + 4),
    height = max(5, nrow(heat_mat) * 0.42 + 2.5)
  )
}
readr::write_csv(
  as.data.frame(heat_mat) |> tibble::rownames_to_column("ModuleColor"),
  file.path(dir_tables, "T02_FigA_module_tier_pct.csv")
)
cat("✅ Figure A sauvegardée (tous les modules)\n\n")

##############################
## PARTIE 7 — FIGURE B
## Scatter kME vs log2FC
## Les modules sélectionnés sont mis en évidence
##############################
cat("════════════════════════════════════════\n")
cat("PARTIE 7 — Figure B : scatter kME vs log2FC\n")
cat("════════════════════════════════════════\n")

scatter_df <- integr_df |>
  dplyr::filter(!is.na(kME_own), !is.na(log2FoldChange),
                !is.na(ModuleColor), ModuleColor != "grey") |>
  dplyr::mutate(
    InSelected = ModuleColor %in% selected_modules
  )

## Labels : Tier1_both dans modules sélectionnés, FDR fort, log2FC extrême
top_labels <- scatter_df |>
  dplyr::filter(
    Tier_Global == "Tier1_both",
    InSelected,
    !is.na(padj), padj < 1e-4,
    abs(log2FoldChange) > quantile(abs(scatter_df$log2FoldChange),
                                   0.90, na.rm = TRUE)
  ) |>
  dplyr::arrange(padj, dplyr::desc(abs(log2FoldChange))) |>
  dplyr::slice_head(n = 20)

p_scatter <- ggplot2::ggplot(
  scatter_df,
  ggplot2::aes(x = kME_own, y = log2FoldChange, colour = Tier_Global)
) +
  ## Fond — NS et Tier3, modules non sélectionnés
  ggplot2::geom_point(
    data  = dplyr::filter(scatter_df, Tier_Global %in% c("NS","Tier3"),
                          !InSelected),
    size  = 0.5, alpha = 0.15
  ) +
  ## Modules non sélectionnés — tiers significatifs, plus transparents
  ggplot2::geom_point(
    data  = dplyr::filter(scatter_df, !Tier_Global %in% c("NS","Tier3"),
                          !InSelected),
    ggplot2::aes(size = -log10(pmax(padj, 1e-300))),
    alpha = 0.35
  ) +
  ## Modules sélectionnés — mis en avant
  ggplot2::geom_point(
    data  = dplyr::filter(scatter_df, !Tier_Global %in% c("NS","Tier3"),
                          InSelected),
    ggplot2::aes(size = -log10(pmax(padj, 1e-300))),
    alpha = 0.90
  ) +
  ggrepel::geom_text_repel(
    data              = top_labels,
    ggplot2::aes(label = Gene),
    colour            = "black",
    fontface          = "italic",
    size              = 2.5,
    max.overlaps      = 25,
    segment.linewidth = 0.3,
    segment.colour    = "grey60",
    box.padding       = 0.40,
    force             = 2
  ) +
  ggplot2::geom_hline(yintercept = 0, colour = "grey40", linewidth = 0.4) +
  ggplot2::geom_vline(xintercept = 0.80, linetype = "dashed",
                      colour = "grey50", linewidth = 0.4) +
  ggplot2::annotate("text", x = 0.81,
                    y = max(scatter_df$log2FoldChange, na.rm=TRUE) * 0.95,
                    label = "kME = 0.80", hjust = 0, size = 2.8,
                    colour = "grey50") +
  ggplot2::scale_colour_manual(values = TIER_COLORS, drop = FALSE,
                               name = "LOO tier") +
  ggplot2::scale_size_continuous(range = c(0.8, 6),
                                 name  = expression(-log[10](FDR)),
                                 breaks = c(2, 5, 10)) +
  ggplot2::labs(
    title    = "Integration LOO–WGCNA",
    subtitle = paste0("Modules sélectionnés mis en avant : ",
                      paste(selected_modules, collapse=", ")),
    x = "Module membership (kME)",
    y = expression(log[2]~"fold change")
  ) +
  theme_pub(base_size = 11) +
  ggplot2::theme(legend.position = "right")

save_gg(p_scatter, file.path(dir_plots, "FigB_Scatter_kME_log2FC"),
        width = 8.5, height = 6.5)
cat("✅ Figure B sauvegardée\n\n")

##############################
## PARTIE 8 — EXPORT CYTOSCAPE
## Un fichier nœuds + arêtes par module sélectionné
##############################
cat("════════════════════════════════════════\n")
cat("PARTIE 8 — Export Cytoscape\n")
cat("════════════════════════════════════════\n\n")

## Détection méthode arêtes
edge_method_used <- if (CYTO_EDGE_METHOD == "auto") {
  if (has_tom) "tom" else if (!is.null(expr_mat)) "cor" else "kme_product"
} else CYTO_EDGE_METHOD
cat("Méthode arêtes :", edge_method_used, "\n\n")

## Helper TOM
load_tom_edges <- function(mod_col, tom_directory, quantile_thr) {
  candidates <- list.files(
    tom_directory,
    pattern    = paste0(mod_col, ".*edges.*TOM\\.csv|edges.*", mod_col, ".*TOM\\.csv"),
    full.names = TRUE
  )
  if (length(candidates) == 0) return(NULL)
  tom <- readr::read_csv(candidates[1], show_col_types = FALSE)
  if (!"weight" %in% colnames(tom)) {
    wt_col <- colnames(tom)[sapply(colnames(tom), function(x) is.numeric(tom[[x]]))]
    if (length(wt_col) == 0) return(NULL)
    tom <- dplyr::rename(tom, weight = dplyr::all_of(wt_col[1]))
  }
  if (!"source" %in% colnames(tom)) {
    if (all(c("fromNode","toNode") %in% colnames(tom)))
      tom <- dplyr::rename(tom, source = fromNode, target = toNode)
    else return(NULL)
  }
  thr <- quantile(tom$weight, probs = quantile_thr, na.rm = TRUE)
  tom <- dplyr::filter(tom, weight >= thr)
  tom$edge_type <- "co-expression_TOM"
  tom[, c("source","target","weight","edge_type")]
}

## Helper corrélation
compute_cor_edges <- function(genes, mat, threshold) {
  genes_avail <- intersect(genes, rownames(mat))
  if (length(genes_avail) < 2) return(NULL)
  cor_mat <- cor(t(mat[genes_avail, , drop = FALSE]),
                 use = "pairwise.complete.obs")
  idx <- which(upper.tri(cor_mat), arr.ind = TRUE)
  df <- data.frame(
    source    = rownames(cor_mat)[idx[,1]],
    target    = colnames(cor_mat)[idx[,2]],
    weight    = cor_mat[idx],
    edge_type = "co-expression_cor",
    stringsAsFactors = FALSE
  )
  dplyr::filter(df, abs(weight) >= threshold)
}

## Résumé final
all_node_tables <- list()
all_edge_tables <- list()

for (mod_col in selected_modules) {
  
  cat("─── Module :", mod_col, "───────────────────────────────\n")
  
  ## Stats du module pour info
  mod_info <- module_summary |> dplyr::filter(ModuleColor == mod_col)
  if (nrow(mod_info) > 0) {
    cat(sprintf("  FDR lmerTest = %s (%s) | beta = %+.3f | N = %d | T1both = %d (%.1f%%)\n",
                formatC(mod_info$FDR[1], format="e", digits=2),
                mod_info$FDR_sig[1],
                dplyr::coalesce(mod_info$betaProtection[1], 0),
                dplyr::coalesce(mod_info$N_genes[1], 0L),
                dplyr::coalesce(mod_info$N_Tier1_both[1], 0L),
                dplyr::coalesce(mod_info$Pct_T1both[1], 0)))
  }
  
  ## ── Nœuds ──────────────────────────────────────────────────────────────
  nodes_raw <- integr_df |>
    dplyr::filter(ModuleColor == mod_col, !is.na(kME_own),
                  kME_own >= CYTO_KME_MIN) |>
    dplyr::arrange(dplyr::desc(kME_own)) |>
    dplyr::slice_head(n = CYTO_MAX_NODES) |>
    dplyr::distinct(Gene, .keep_all = TRUE)
  
  n_nodes <- nrow(nodes_raw)
  cat("  Nœuds (kME ≥", CYTO_KME_MIN, ") :", n_nodes, "\n")
  
  if (n_nodes < 3) {
    cat("  ⚠️  < 3 nœuds — module ignoré\n\n"); next
  }
  
  nodes_out <- nodes_raw |>
    dplyr::mutate(
      Tier      = as.character(dplyr::coalesce(as.character(Tier_Global), "NS")),
      NodeColor = dplyr::coalesce(TIER_HEX[Tier], "#BDBDBD"),
      NodeSize  = dplyr::case_when(
        kME_own >= 0.80 ~ 60,
        kME_own >= 0.60 ~ 40,
        TRUE            ~ 25
      ),
      NodeShape = dplyr::case_when(
        Status == "Up"   ~ "ELLIPSE",
        Status == "Down" ~ "RECTANGLE",
        TRUE             ~ "DIAMOND"
      ),
      ## Étiquette = Tier1_both ou hub (kME ≥ 0.80)
      NodeLabel = dplyr::if_else(
        Tier == "Tier1_both" | kME_own >= 0.80, Gene, ""
      ),
      Module_FDR_str = ifelse(is.na(Module_FDR), "NS",
                              formatC(Module_FDR, format="e", digits=2)),
      log2FC_str     = ifelse(is.na(log2FoldChange), "NA",
                              as.character(round(log2FoldChange, 3))),
      FDR_edgeR_str  = ifelse(is.na(padj), "NS",
                              formatC(padj, format="e", digits=2))
    ) |>
    dplyr::select(
      name      = Gene,
      Module    = ModuleColor,
      Tier, NodeColor, NodeSize, NodeShape, NodeLabel,
      kME       = kME_own,
      GS        = GS_Protection,
      log2FC    = log2FoldChange,
      FDR_edgeR = padj,
      Direction = Status,
      aveLogCPM, LOO_Score_P, LOO_Score_N,
      Module_FDR, Module_beta, Module_FDR_str, log2FC_str, FDR_edgeR_str
    )
  
  ## ── Arêtes ─────────────────────────────────────────────────────────────
  genes_mod  <- nodes_out$name
  edges_raw  <- if (edge_method_used == "tom") {
    load_tom_edges(mod_col, tom_dir, CYTO_TOM_QUANTILE)
  } else if (edge_method_used == "cor" && !is.null(expr_mat)) {
    compute_cor_edges(genes_mod, expr_mat, CYTO_COR_THRESHOLD)
  } else NULL
  
  ## Fallback kME-product
  if (is.null(edges_raw) || nrow(edges_raw) == 0) {
    cat("  → Fallback kME-product\n")
    kme_vals <- setNames(nodes_out$kME, nodes_out$name)
    pairs    <- utils::combn(genes_mod, 2)
    edges_raw <- data.frame(
      source    = pairs[1,],
      target    = pairs[2,],
      weight    = kme_vals[pairs[1,]] * kme_vals[pairs[2,]],
      edge_type = "kME_product",
      stringsAsFactors = FALSE
    )
    thr_kp    <- quantile(edges_raw$weight, 0.75, na.rm = TRUE)
    edges_raw <- dplyr::filter(edges_raw, weight >= thr_kp)
  }
  
  ## Filtrer aux nœuds retenus + cap absolu
  edges_out <- edges_raw |>
    dplyr::filter(source %in% genes_mod, target %in% genes_mod) |>
    dplyr::arrange(dplyr::desc(weight)) |>
    dplyr::slice_head(n = CYTO_MAX_EDGES)
  
  n_edges <- nrow(edges_out)
  cat("  Arêtes :", n_edges, "\n")
  cat("  Nœuds Tier1_both :", sum(nodes_out$Tier == "Tier1_both"),
      "| kME ≥ 0.80 :", sum(nodes_out$kME >= 0.80), "\n\n")
  
  ## Sauvegarder
  readr::write_csv(nodes_out,
                   file.path(dir_cyto, paste0("nodes_", mod_col, ".csv")))
  readr::write_csv(edges_out,
                   file.path(dir_cyto, paste0("edges_", mod_col, ".csv")))
  
  all_node_tables[[mod_col]] <- nodes_out
  all_edge_tables[[mod_col]] <- edges_out
}

## Légende couleurs
legend_df <- data.frame(
  Tier      = names(TIER_HEX),
  NodeColor = unname(TIER_HEX),
  Shape     = c("ELLIPSE/RECT/DIAMOND","ELLIPSE/RECT/DIAMOND","ELLIPSE/RECT/DIAMOND",
                "ELLIPSE/RECT/DIAMOND","ELLIPSE/RECT/DIAMOND","DIAMOND"),
  Description = c(
    "Tier1_both   — robuste LOO-P ET LOO-N (prioritaire)",
    "Tier1_P_only — robuste LOO-P seulement",
    "Tier1_N_only — robuste LOO-N seulement",
    "Tier2        — partiellement robuste",
    "Tier3        — signal génotype-dépendant",
    "NS           — non différentiel"
  )
)
readr::write_csv(legend_df, file.path(dir_cyto, "LEGEND_Tier_colors.csv"))

## Instructions Cytoscape
writeLines(c(
  "═══════════════════════════════════════════════════════════════",
  "GUIDE D'IMPORT CYTOSCAPE — v5",
  "═══════════════════════════════════════════════════════════════",
  "",
  "ÉTAPE 1 — Importer les arêtes",
  "  File > Import > Network from File",
  "  Fichier : edges_{module}.csv",
  "  → source = Source Node | target = Target Node",
  "  → weight = Edge Attribute | Undirected",
  "",
  "ÉTAPE 2 — Importer les nœuds",
  "  File > Import > Table from File",
  "  Fichier : nodes_{module}.csv",
  "  Cible : Node Table | Key = 'name' (des deux côtés)",
  "",
  "ÉTAPE 3 — Styles visuels (Passthrough Mapping)",
  "  Fill Color → NodeColor    (hex direct, pas de gradient à créer)",
  "  Size       → NodeSize     (60 = hub | 40 = intermédiaire | 25 = périphérique)",
  "  Shape      → NodeShape    (ELLIPSE=Up | RECTANGLE=Down | DIAMOND=NS)",
  "  Label      → NodeLabel    (vide pour NS non-hub)",
  "",
  "ÉTAPE 4 — Layout",
  "  Layout > Prefuse Force-Directed (weight = weight)",
  "",
  "ÉTAPE 5 — Épaisseur arêtes",
  "  Style > Edge > Width > Continuous Mapping sur weight",
  "  Min = 0.5 | Max = 3.0",
  "",
  "LÉGENDE (voir LEGEND_Tier_colors.csv)",
  "  #1A237E = Tier1_both   #E53935 = Tier1_P_only",
  "  #00897B = Tier1_N_only #F57F17 = Tier2",
  "  #78909C = Tier3        #BDBDBD = NS"
), file.path(dir_cyto, "INSTRUCTIONS_Cytoscape.txt"))

cat("✅ Fichiers Cytoscape sauvegardés\n\n")

## ── Résumé final ────────────────────────────────────────────────────────────
cat("════════════════════════════════════════\n")
cat("RÉSUMÉ FINAL\n")
cat("════════════════════════════════════════\n")
cat("Mode sélection :", if (length(MODULES_MANUAL) > 0) "MANUEL" else "AUTO", "\n")
cat("Modules traités :", length(all_node_tables), "\n\n")
for (mod_col in names(all_node_tables)) {
  nn  <- nrow(all_node_tables[[mod_col]])
  ne  <- nrow(all_edge_tables[[mod_col]])
  nt1 <- sum(all_node_tables[[mod_col]]$Tier == "Tier1_both")
  cat(sprintf("  %-15s : %3d nœuds (%d Tier1_both) | %d arêtes\n",
              mod_col, nn, nt1, ne))
}
cat("\nRésultats dans :", out_dir, "\n")
cat("════════════════════════════════════════\n")



## ══════════════════════════════════════════════════════════════════════════
## PARTIE 5B — SCORE COMPOSITE DE PRIORITÉ DES MODULES
## ══════════════════════════════════════════════════════════════════════════
##
## Formule (3 composantes, sans beta) :
##   Score = 0.45 × S_FDR + 0.40 × S_Pct_T1both + 0.15 × S_N_T1both
##
##   S_FDR  = -log10(FDR lmerTest)   → significativité statistique
##   S_Pct  = % Tier1_both du module → enrichissement en DEG robustes LOO
##   S_N    = N Tier1_both (absolu)  → poids biologique brut
##
##   Chaque composante est normalisée 0→1 (valeur / max de la série)
##   avant pondération, puis multipliée par 100.
## ══════════════════════════════════════════════════════════════════════════

SCORE_WEIGHTS <- list(
  fdr = 0.45,
  pct = 0.40,
  n   = 0.15
)

cat("════════════════════════════════════════\n")
cat("PARTIE 5B — Score composite modules\n")
cat("════════════════════════════════════════\n")

## ── Calcul des composantes ──────────────────────────────────────────────────
tier1_counts <- integr_df |>
  dplyr::filter(!is.na(ModuleColor), ModuleColor != "grey") |>
  dplyr::group_by(ModuleColor) |>
  dplyr::summarise(
    N_genes      = dplyr::n(),
    N_Tier1_both = sum(Tier_Global == "Tier1_both",   na.rm = TRUE),
    N_Tier1_P    = sum(Tier_Global == "Tier1_P_only", na.rm = TRUE),
    N_Tier1_N    = sum(Tier_Global == "Tier1_N_only", na.rm = TRUE),
    N_Tier2      = sum(Tier_Global == "Tier2",        na.rm = TRUE),
    Pct_T1both   = round(100 * N_Tier1_both / dplyr::n(), 2),
    .groups = "drop"
  )

## Pré-calcul des maxima hors mutate (évite les problèmes de longueur)
tmp_base <- me_df |>
  dplyr::filter(!is.na(FDR), ModuleColor != "grey") |>
  dplyr::select(ME, ModuleColor, FDR) |>
  dplyr::left_join(tier1_counts, by = "ModuleColor") |>
  dplyr::mutate(
    raw_FDR = -log10(FDR),
    raw_Pct = Pct_T1both,
    raw_N   = as.numeric(N_Tier1_both)
  )

max_FDR <- max(tmp_base$raw_FDR, na.rm = TRUE)
max_Pct <- max(tmp_base$raw_Pct, na.rm = TRUE)
max_N   <- max(tmp_base$raw_N,   na.rm = TRUE)

composite_df <- tmp_base |>
  dplyr::mutate(
    ## Normalisation 0→1
    S_FDR = raw_FDR / max_FDR,
    S_Pct = raw_Pct / max_Pct,
    S_N   = raw_N   / max_N,
    
    ## Score composite (0–100)
    Score_composite = round(
      (SCORE_WEIGHTS$fdr * S_FDR +
         SCORE_WEIGHTS$pct * S_Pct +
         SCORE_WEIGHTS$n   * S_N) * 100,
      1
    ),
    
    ## Contributions individuelles
    C_FDR = round(SCORE_WEIGHTS$fdr * S_FDR * 100, 1),
    C_Pct = round(SCORE_WEIGHTS$pct * S_Pct * 100, 1),
    C_N   = round(SCORE_WEIGHTS$n   * S_N   * 100, 1),
    
    ## Catégories
    FDR_sig = dplyr::case_when(
      FDR < 0.001 ~ "***",
      FDR < 0.01  ~ "**",
      FDR < 0.05  ~ "*",
      FDR < 0.10  ~ ".",
      TRUE        ~ "ns"
    ),
    Priority = dplyr::case_when(
      Score_composite >= 50 ~ "Priorité 1",
      Score_composite >= 25 ~ "Priorité 2",
      Score_composite >= 10 ~ "Priorité 3",
      TRUE                  ~ "Faible"
    ),
    Priority = factor(Priority,
                      levels = c("Priorité 1","Priorité 2","Priorité 3","Faible"))
  ) |>
  dplyr::arrange(dplyr::desc(Score_composite))

## ── Export ──────────────────────────────────────────────────────────────────
readr::write_csv(composite_df,
                 file.path(dir_tables, "T_Composite_score_modules.csv"))

## ── Affichage console ───────────────────────────────────────────────────────
cat("\nScore composite par module (décroissant) :\n")
cat(sprintf("%-15s %7s %-5s %7s %7s %7s %6s %5s\n",
            "Module","Score","Sig","C_FDR","C_Pct","C_N","T1both","Pct%"))
cat(strrep("─", 62), "\n")
for (i in seq_len(nrow(composite_df))) {
  r <- composite_df[i,]
  cat(sprintf("%-15s %7.1f %-5s %7.1f %7.1f %7.1f %6d %4.1f%%\n",
              r$ModuleColor, r$Score_composite, r$FDR_sig,
              r$C_FDR, r$C_Pct, r$C_N,
              dplyr::coalesce(r$N_Tier1_both, 0L),
              dplyr::coalesce(r$Pct_T1both, 0)))
}
cat(strrep("─", 62), "\n")
cat(sprintf("Poids : FDR=%.2f | Pct_T1both=%.2f | N_T1both=%.2f\n",
            SCORE_WEIGHTS$fdr, SCORE_WEIGHTS$pct, SCORE_WEIGHTS$n))
cat("\n")

## Modules sélectionnés automatiquement via le score
selected_by_score <- composite_df |>
  dplyr::filter(Score_composite >= 25) |>
  dplyr::pull(ModuleColor)

cat("Modules Score ≥ 25 (Priorité 2+) :",
    paste(selected_by_score, collapse = ", "), "\n\n")

## ══════════════════════════════════════════════════════════════════════════
## PARTIE 5C — FIGURE : Score composite décomposé
## ══════════════════════════════════════════════════════════════════════════
cat("════════════════════════════════════════\n")
cat("PARTIE 5C — Figure score composite\n")
cat("════════════════════════════════════════\n")

score_long <- composite_df |>
  dplyr::select(ModuleColor, Score_composite, Priority,
                C_FDR, C_Pct, C_N, FDR_sig) |>
  tidyr::pivot_longer(
    cols      = c(C_FDR, C_Pct, C_N),
    names_to  = "Composante",
    values_to = "Valeur"
  ) |>
  dplyr::mutate(
    Composante = factor(
      Composante,
      levels = c("C_FDR","C_Pct","C_N"),
      labels = c("FDR lmerTest (×0.45)",
                 "% Tier1_both (×0.40)",
                 "N Tier1_both (×0.15)")
    ),
    ModuleColor = factor(ModuleColor,
                         levels = rev(composite_df$ModuleColor))
  )

comp_colors <- c(
  "FDR lmerTest (×0.45)" = "#5C4AB7",
  "% Tier1_both (×0.40)" = "#1D9E75",
  "N Tier1_both (×0.15)" = "#E59400"
)

mod_label_colors <- setNames(
  ifelse(composite_df$ModuleColor %in% grDevices::colors(),
         composite_df$ModuleColor, "#444444"),
  composite_df$ModuleColor
)

p_score <- ggplot2::ggplot(
  score_long,
  ggplot2::aes(y = ModuleColor, x = Valeur, fill = Composante)
) +
  ggplot2::annotate("rect", xmin = 50, xmax = Inf,
                    ymin = -Inf, ymax = Inf,
                    fill = "#E8F5E9", alpha = 0.35) +
  ggplot2::annotate("rect", xmin = 25, xmax = 50,
                    ymin = -Inf, ymax = Inf,
                    fill = "#FFF8E1", alpha = 0.35) +
  ggplot2::geom_vline(xintercept = c(25, 50), linetype = "dashed",
                      colour = "grey70", linewidth = 0.4) +
  ggplot2::geom_col(width = 0.72, colour = NA) +
  ## Score total dans la barre
  ggplot2::geom_text(
    data = composite_df |>
      dplyr::filter(Score_composite >= 8) |>
      dplyr::mutate(ModuleColor = factor(ModuleColor,
                                         levels = rev(composite_df$ModuleColor))),
    ggplot2::aes(y = ModuleColor, x = Score_composite / 2,
                 label = Score_composite, fill = NULL),
    hjust = 0.5, size = 2.8, colour = "white", fontface = "bold"
  ) +
  ## Étoiles FDR à droite
  ggplot2::geom_text(
    data = composite_df |>
      dplyr::mutate(ModuleColor = factor(ModuleColor,
                                         levels = rev(composite_df$ModuleColor))),
    ggplot2::aes(y = ModuleColor, x = Score_composite + 1.5,
                 label = FDR_sig, fill = NULL),
    hjust = 0, size = 3, colour = "grey30", fontface = "bold"
  ) +
  ggplot2::annotate("text", x = 51, y = 0.6,
                    label = "Priorité 1", hjust = 0,
                    size = 2.8, colour = "#388E3C", fontface = "italic") +
  ggplot2::annotate("text", x = 26, y = 0.6,
                    label = "Priorité 2", hjust = 0,
                    size = 2.8, colour = "#F57F17", fontface = "italic") +
  ggplot2::scale_fill_manual(values = comp_colors, name = "Composante") +
  ggplot2::scale_x_continuous(
    limits = c(0, 105),
    breaks = c(0, 25, 50, 75, 100),
    expand = ggplot2::expansion(mult = c(0, 0.01))
  ) +
  ggplot2::labs(
    title    = "Priorité des modules WGCNA — score composite",
    subtitle = paste0(
      "Score = 0.45 × FDR lmerTest + 0.40 × % Tier1_both + 0.15 × N Tier1_both\n",
      "Chaque composante normalisée 0→1  |  ns / . / * / ** / *** = FDR lmerTest"
    ),
    x = "Score composite (0–100)",
    y = NULL
  ) +
  theme_pub(base_size = 11) +
  ggplot2::theme(
    axis.text.y        = ggplot2::element_text(
      colour = mod_label_colors[levels(score_long$ModuleColor)],
      face   = "bold", size = 11
    ),
    legend.position    = "bottom",
    legend.direction   = "horizontal",
    panel.grid.major.x = ggplot2::element_line(colour = "grey92", linewidth = 0.4),
    panel.grid.major.y = ggplot2::element_blank()
  )

n_mods <- nrow(composite_df)
save_gg(p_score,
        file.path(dir_plots, "FigC_Composite_score_modules"),
        width = 9, height = max(5, n_mods * 0.45 + 2.5))

## ── Heatmap des composantes normalisées (figure supplémentaire) ─────────────
score_mat <- composite_df |>
  dplyr::select(ModuleColor, S_FDR, S_Pct, S_N) |>
  as.data.frame()
rownames(score_mat) <- score_mat$ModuleColor
score_mat$ModuleColor <- NULL
colnames(score_mat) <- c("FDR", "% T1both", "N T1both")
score_mat <- as.matrix(score_mat)

ann_row_score <- composite_df |>
  dplyr::select(ModuleColor, Priority, Score_composite) |>
  dplyr::rename(Score = Score_composite) |>
  as.data.frame()
rownames(ann_row_score) <- ann_row_score$ModuleColor
ann_row_score$ModuleColor <- NULL

priority_colors <- c(
  "Priorité 1" = "#388E3C",
  "Priorité 2" = "#F57F17",
  "Priorité 3" = "#78909C",
  "Faible"     = "#E0E0E0"
)

for (ext in c("pdf","png")) {
  pheatmap::pheatmap(
    score_mat,
    annotation_row    = ann_row_score,
    annotation_colors = list(Priority = priority_colors),
    color             = grDevices::colorRampPalette(
      c("#F5F5F5","#7986CB","#1A237E"))(100),
    cluster_rows      = FALSE,
    cluster_cols      = FALSE,
    border_color      = "grey90",
    fontsize          = 10,
    display_numbers   = TRUE,
    number_format     = "%.2f",
    number_color      = "grey20",
    main              = "Composantes normalisées du score composite",
    filename          = file.path(dir_plots,
                                  paste0("FigC_supp_score_heatmap.", ext)),
    width  = 6,
    height = max(4, nrow(score_mat) * 0.42 + 2.5)
  )
}

cat("✅ Figure score composite sauvegardée (FigC)\n\n")

## ── Mise à jour selected_modules si mode AUTO ───────────────────────────────
if (length(MODULES_MANUAL) == 0) {
  selected_modules <- selected_by_score
  if (length(selected_modules) == 0) {
    cat("⚠️  Aucun module score ≥ 25 — top", MODULES_AUTO_N, "par score\n")
    selected_modules <- composite_df |>
      dplyr::slice_head(n = MODULES_AUTO_N) |>
      dplyr::pull(ModuleColor)
  }
  cat("▶  Mode AUTO (score composite ≥ 25) :",
      paste(selected_modules, collapse = ", "), "\n\n")
}